name: Code Quality Check

on:
  push: # すべてのコミットをチェック
    branches: ["*"]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-app
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: TypeScript Compile Check (VSCodeの赤線対策)
        run: npm run tsc --noEmit

      - name: ESLint Check
        run: npm run lint
